### Listar usuários
GET localhost:8080/api/users

### Cadastra um usuário
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "Vini",
  "email": "Vini@gmail.com",
  "password": "vini0000"
}

### Lista o usuário 2
GET localhost:8080/api/users/102

### Lista o próprio usuário
GET localhost:8080/api/users/me
Authorization: Bearer {{token}}

### Login
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "Vini@gmail.com",
  "password": "vini0000"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)
%}

### Login como Admin
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "admin@authserver.com",
  "password": "admin"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)
%}

### Exclui o usuário
DELETE localhost:8080/api/users/2
Authorization: Bearer {{token}}

### Exclui o evento 2
DELETE localhost:8080/api/users/events/2
Authorization: Bearer {{token}}

### Cria categoria
POST localhost:8080/api/events/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Rpg"
}

### Cria evento
POST localhost:8080/api/users/events
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Rpg",
  "local": "Minha casa",
  "hour": "12:00",
  "description": "Traga os dados",
  "creatorId": 102,
  "categoryId": 56
}